---
- hosts: debiantest

  become: true
  become_method: su
  become_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install packages
      apt:
        name: 
          - ncdu
          - git
          - vim
          - htop
          - sudo
          - wget
          - nfs-common
          - ncdu
          - autofs
        state: present

    - name: Install mail packages
      apt:
        name: 
          - msmtp-mta
          - bsd-mailx
        state: present

    - name: Configure mail server
      copy:
        dest: "/etc/msmtprc"
        mode: 0644
        # owner: root
        content: |
          # Set default values for all following accounts.
          defaults
          port 587
          tls on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          logfile -

          account mailserver
          host {{ debian_smtp_host }}
          from {{ debian_smtp_user }}
          auth on
          user {{ debian_smtp_user }}
          password {{ debian_smtp_password }}

          # Set a default account
          account default : mailserver

    - name: Add user to sudoers
      user:
        name: '{{ debian_user }}'
        groups: sudo
        append: yes

    - name: Setting VIM
      copy:
        dest: "{{ item }}"
        content: |
          source $VIMRUNTIME/defaults.vim
          set mouse-=a
      with_items:
        - /home/{{ debian_user }}/.vimrc
        - /root/.vimrc

    - name: Add aliases
      blockinfile: 
        state: present
        insertafter: EOF
        dest: "{{ item }}"
        content: |
          alias ll='ls -lah --color'
      with_items:
        - /home/{{ debian_user }}/.bashrc
        - /root/.bashrc

    - name: Chown all user folders
      shell: chown -R {{ debian_user }}:{{ debian_user }} /home/{{ debian_user }}