---
- name: Check deluge
  hosts: docker
  become: false
  tasks:
    - name: Launch curl on deluge url (check http 200)
      command: >
        curl -s --connect-timeout 30 --max-time 30 --retry-connrefused --retry-all-errors --fail --retry 10 --retry-delay 5 --retry-max-time 120 {{ deluge_url }}
      register: curl_output
      ignore_errors: yes

    - name: Get gluetun health check
      shell: docker inspect {{ gluetun_ct_name }} | jq -r '.[].State.Health.Status'
      register: gluetun_health
      when: curl_output is failed

    - name: Restart deluge
      command: docker restart {{ deluge_ct_name }}
      when: curl_output is failed and gluetun_health.stdout == "healthy"