---
- hosts: all

  tasks:
    - name: Get Discorder
      become: true
      get_url: 
        url: "https://gist.githubusercontent.com/OlivierProTips/fd3f645e9bed6073be01f244d3e8ef7f/raw/" 
        dest: "/usr/local/bin/discorder"
        mode: "+x"

    - name: Create .local
      file: 
        mode: 0755
        path: /home/{{ debian_user }}/.local
        state: directory

    - name: Add token
      copy: 
        dest: /home/{{ debian_user }}/.local/discorder.token
        content: "{{ discorder_webhook }}"