---
- hosts: all

  become: true
  tasks:
    - name: apt install some apps
      apt:
        name: 
          - ncdu
          - borgbackup
          - python3-pip
        state: present

    - name: apt remove some apps
      apt:
        name: 
          - borgmatic
        state: absent

    - name: pip install some apps
      pip:
        name:
          - borgmatic
        state: present