---
- hosts: kali

  become: true

  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Wait for sudo
      become: yes
      shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Upgrade apt packages
      become: true
      apt:
        upgrade: yes

    - name: Download arm vscode
      get_url: url=https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64 dest=/tmp/vscode.deb
      when: ansible_architecture == aarch64 OR ansible_architecture == arm64

    - name: Download x64 vscode
      get_url: url=https://code.visualstudio.com/sha/download?build=stable&os=x64 dest=/tmp/vscode.deb
      when: ansible_architecture != aarch64 AND ansible_architecture != arm64

    - name: Install VSCode
      apt:
        deb: /tmp/vscode.deb