---
- hosts: kali

  become: true

  tasks:
    # - name: Update and upgrade apt packages
    #   apt:
    #     upgrade: yes
    #     update_cache: yes
    #     cache_valid_time: 86400 #One day

    - name: Download arm vscode
      get_url: url=https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64 dest=/tmp/vscode.deb
      when: ansible_architecture == aarch64 OR ansible_architecture == arm64

    - name: Download x64 vscode
      get_url: url=https://code.visualstudio.com/sha/download?build=stable&os=x64 dest=/tmp/vscode.deb
      when: ansible_architecture != aarch64 AND ansible_architecture != arm64

    - name: Install VSCode
      apt:
        deb: /tmp/vscode.deb