---
- name: Transférer les données entre deux Pi-hole
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Authentification sur PiHole Master
      uri:
        url: "{{ pihole_master }}/api/auth"
        method: POST
        headers:
          accept: "application/json"
          content-type: "application/json"
        body_format: json
        body:
          password: "{{ pihole_master_password }}"
        return_content: yes
        status_code: [200, 201]
      register: auth_pihole_master
      ignore_errors: yes
      check_mode: no

    - name: Debug réponse brute Auth PiHole Master
      debug:
        var: auth_pihole_master

    - name: Vérification de l'authentification sur PiHole Master
      fail:
        msg: "Authentification échouée. Réponse API: {{ auth_pihole_master }}"
      when: auth_pihole_master.failed or auth_pihole_master.json is not defined or 'sid' not in auth_pihole_master.json

    - name: Récupération des données depuis PiHole Master
      uri:
        url: "{{ pihole_master }}/api/teleporter"
        method: GET
        headers:
          accept: "application/zip"
          sid: "{{ auth_pihole_master.json.session.sid }}"
        return_content: yes
      register: teleporter_data
      ignore_errors: yes
      check_mode: no
      changed_when: false

    - name: Vérification de la récupération des données
      fail:
        msg: "Échec du téléchargement. Réponse API: {{ teleporter_data }}"
      when: teleporter_data.failed

    - name: Sauvegarde du fichier téléchargé
      copy:
        content: "{{ teleporter_data.content }}"
        dest: "/tmp/teleporter.zip"
        mode: '0644'

    - name: Authentification sur PiHole Slave 1
      uri:
        url: "{{ pihole_slave_1 }}/api/auth"
        method: POST
        headers:
          accept: "application/json"
          content-type: "application/json"
        body_format: json
        body:
          password: "{{ pihole_slave_1_password }}"
        return_content: yes
        status_code: [200, 201]
      register: auth_pihole_slave_1
      ignore_errors: yes
      check_mode: no

    - name: Debug réponse brute Auth PiHole Slave 1
      debug:
        var: auth_pihole_slave_1

    - name: Vérification de l'authentification sur PiHole Slave 1
      fail:
        msg: "Authentification échouée. Réponse API: {{ auth_pihole_slave_1 }}"
      when: auth_pihole_slave_1.failed or auth_pihole_slave_1.json is not defined or 'sid' not in auth_pihole_slave_1.json

    - name: Envoi du fichier vers PiHole Slave 1
      uri:
        url: "{{ pihole_slave_1 }}/api/teleporter"
        method: POST
        headers:
          accept: "application/json"
          sid: "{{ auth_pihole_slave_1.json.session.sid }}"
        body_format: form-multipart
        src: "/tmp/teleporter.zip"
        return_content: yes
      register: upload_result
      ignore_errors: yes
      check_mode: no

    - name: Vérification de l'envoi des données
      fail:
        msg: "Échec de l'envoi. Réponse API: {{ upload_result }}"
      when: upload_result.failed

    - name: Afficher le résultat de l'envoi
      debug:
        var: upload_result
