---
- hosts: localhost

  tasks:
  - name: Show hostname
    debug:
      msg: "Host: {{ ansible_hostname }} FQDN: {{ ansible_nodename }}"

  - name: Test print
    debug:
      msg:
        - "coucou"
        - "toi"