---
# 0 5 * * *
- hosts: pihole_servers
  become: true

  tasks:
  - name: Get pihole version
    ansible.builtin.command: pihole -v
    register: pihole_version
  - set_fact:
      pihole: "{{ pihole_version.stdout | regex_search('Pi-hole version is v(.*) \\(Latest: v.*\\)', '\\1', multiline=true) | first }}"
      pihole_latest: "{{ pihole_version.stdout | regex_search('Pi-hole version is v.* \\(Latest: v(.*)\\)', '\\1', multiline=true) | first }}"
      lte: "{{ pihole_version.stdout | regex_search('AdminLTE version is v(.*) \\(Latest: v.*\\)', '\\1', multiline=true) | first }}"
      lte_latest: "{{ pihole_version.stdout | regex_search('AdminLTE version is v.* \\(Latest: v(.*)\\)', '\\1', multiline=true) | first }}"
      ftl: "{{ pihole_version.stdout | regex_search('FTL version is v(.*) \\(Latest: v.*\\)', '\\1', multiline=true) | first }}"
      ftl_latest: "{{ pihole_version.stdout | regex_search('FTL version is v.* \\(Latest: v(.*)\\)', '\\1', multiline=true) | first }}"

  - name: Update pihole
    ansible.builtin.command: pihole -up
    when: pihole != pihole_latest or lte != lte_latest or ftl != ftl_latest

  - name: send discord message when PiHole is updated
    uri:
      url: "{{ discord_webhook }}"
      method: POST
      body_format: json
      body: '{"content": "PiHole Updated on {{ inventory_hostname }}:\nPiHole: {{ pihole }} 👉 {{ pihole_latest }}\nLTE: {{ lte }} 👉 {{ lte_latest }}\nFTL: {{ ftl }} 👉 {{ ftl_latest }}"}'
      headers:
        Content-Type: application/json
      status_code: 204
    when: pihole != pihole_latest or lte != lte_latest or ftl != ftl_latest